## Creating tensors

#### The first thing we're going to create is a **scalar**. A scalar is a **single number** and in tensor-speak it's a zero dimension tensor.

In [ ]:
scalar = torch.tensor(7)
scalar

Output: tensor(7)

We can check the **dimensions of a tensor** using the ```ndim``` attribute.

In [ ]:
scalar.ndim

Output: 0

What if we wanted to **retrieve** the number from the tensor? To do we can use the ```item()``` method.

In [ ]:
scalar.item()

Output: 7

#### Now let's see a **vector**. A vector is a **single dimension** tensor but can contain many numbers.

In [ ]:
vector = torch.tensor([7, 7])
vector

Output: tensor([7, 7])

In [ ]:
vector.ndim

Output: 1

You can tell **the number of dimensions a tensor** in Pytorch has by **the number of square brackets on the outside**

Another important concept for tensors is their ```shape``` attribute. The shape tells you **how the elements inside them are arranged**.

In [ ]:
vector.shape

Output: torch.Size([2])

Our vector has a shape of ```[2]```. This is because of **the two elements we placed inside the square brackets**.

#### Now let's see a **matrix**.

In [ ]:
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

Output: tensor([[ 7,  8],
                [ 9, 10]])

In [ ]:
MATRIX.ndim

Output: 2

In [ ]:
MATRIX.shape

Output: torch.Size([2, 2])

#### How about we create a **tensor**?

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

In [ ]:
TENSOR.ndim

Output: 3

In [ ]:
TENSOR.shape

Output: torch.Size([1, 3, 3])

#### Random tensors

We can create a tensor of random numbers using ```torch.rand()``` and passing in the ```size``` parameter.

In [ ]:
random_tensor = torch.rand(size=(3, 4))
random_tensor, random_tensor.dtype

Output: (tensor([[0.6541, 0.4807, 0.2162, 0.6168],
         [0.4428, 0.6608, 0.6194, 0.8620],
         [0.2795, 0.6055, 0.4958, 0.5483]]),
 torch.float32)

The flexibility of ```torch.rand()``` is that we can adjust the ```size``` to be whatever we want. For example, you want a random tensor in the common image shape of ```[224, 224, 3]``` ```([height, width, channels])```

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

Output: (torch.Size([224, 224, 3]), 3)

#### Zeros and ones

This happens a lot with masking (like masking some of the values in one tensor with zeros to **let a model know not to learn them**). Let's create a tensor full of zeros with ```torch.zeros()```. Again, the ```size``` parameter comes into play. 

In [ ]:
zeros = torch.zeros(size=(3, 4))
zeros, zeros.dtype

Output: (tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

#### Creating a range and tensors like

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100. You can use ```torch.arange(start, end, step)``` to do so.

In [ ]:
zero_to_ten = torch.arange(start=0, end=10, step=1)
zero_to_ten

Output: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Sometimes you might want one tensor of a certain type with the same shape as another tensor. To do so you can use ```torch.zeros_like(input)``` or ```torch.ones_like(input)``` which return a tensor filled with zeros or ones in the same shape as the ```input``` respectively.

In [ ]:
ten_zeros = torch.zeros_like(input=zero_to_ten)
ten_zeros

Output: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Getting information from tensors

Three of the most common attributes you'll want to find out about tensors are:
1. ```shape```
2. ```dtype```
3. ```device```

In [ ]:
some_tensor = torch.rand(3, 4)

print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}")

Output: tensor([[0.4688, 0.0055, 0.8551, 0.0646],
        [0.6538, 0.5157, 0.4071, 0.2109],
        [0.9960, 0.3061, 0.9369, 0.7008]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu

#### Matrix multiplication

Pytorch implements matrix multiplication in the ```torch.matmul()``` method. **You can also use ```torch.mm()``` which is a short for ```torch.matmul()```.**

In [ ]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

Output: torch.Size([3])

|Operation                  | Calculation                            | Code                       |
|---------------------------|----------------------------------------|----------------------------|
|Element-wise multiplication| ```[1*1, 2*2, 3*3]``` = ```[1, 4, 9]```| ```tensor * tensor```      |
|Matrix multiplication      | ```[1*1 + 2*2 + 3*3]``` = ```[14]```   | ```tensor.matmul(tensor)```|

In [ ]:
tensor.matmul(tensor, tensor)

tensor(14)

One of the ways to do this is with a **transpose** (switch the dimensions of a given tensor). You can use ```tensor.T``` - where ```tensor``` is the desired tensor to transpose.

#### Finding the min, max, mean, sum, etc

First we'll create a tensor and then find the max, min, mean and sum of it.

In [ ]:
x = tensor.arange(0, 100, 10)
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Output: Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450

**Note:** You may find some methods such as ```torch.mean()``` require tensors to be in ```torch.float32``` (the most common) or another specific datatype, otherwise the operation will fail.

#### Positional min/max

You can also find the index of a tensor where the max or minimum occurs with ```torch.argmax()``` and ```torch.argmin()``` respectively.

In [ ]:
tensor = torch.arange(10, 100, 10)

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Output: Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0

#### Change tensor datatype

You can change the datatype of tensors using ```torch.Tensor.type(dtype=None)``` where the ```dtype``` parameter is the datatype you'd like to use.

In [ ]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

Output: torch.float32

In [ ]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

Output: tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

#### Reshaping, stacking, squeezing and unsqueezing

Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

|Method                             |                                                                                                      Description|
|-----------------------------------|-----------------------------------------------------------------------------------------------------------------|
|```torch.reshape(input, shape)```  |                  Reshapes ```input``` to ```shape``` (if compatible), can also use ```torch.Tensor.reshape()```.|
|```Tensor.view(shape)```           |Returns a view of the original tensor in a different ```shape``` but shares the same data as the original tensor.|
|```torch.stack(tensors, dim=0)```  | Concatenates a sequence of ```tensors``` along a new dimension (```dim```), all ```tensors``` must be same size.|
|```tensor.squeeze(input)```        |                                             Squeezes ```input``` to remove all the dimenions with value ```1```.|
|```tensor.unsqueeze(input, dim)``` |                                        Returns ```input``` with a dimension value of ```1``` added at ```dim```.|
|```torch.permute(input, dims)```   |              Returns a view of the original ```input``` with its dimensions permuted (rearranged) to ```dims```.|

In [ ]:
import torch
x = torch.arange(1., 8.)
x, x.shape

Output: (tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [ ]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

Output: (tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

We can also change the view with ```torch.view()```

In [ ]:
z = x.view(1, 7)
z, z.shape

Output: (tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

Remember though, changing the view of a tensor with ```torch.view()``` really only creates a new view of the same tensor. **So changing the view changes the original tensor too.**

In [ ]:
# Changing z changes x
z[:, 0] = 5
z, x

Output: (tensor([[5., 2., 3., 4., 5., 6., 7.]]), tensor([5., 2., 3., 4., 5., 6., 7.]))

If we wanted to stack our new tensor on top of itself five times, we could do so with ```tensor.stack()```

In [ ]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

Output: tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

How about **removing all single dimensions from a tensor**? To do so you can use ```torch.squeeze()```

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Output: Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
Previous shape: torch.Size([1, 7])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
New shape: torch.Size([7])

And to do the **reverse** of ```torch.squeeze()``` you can use ```torch.unsqueezq()``` to add a dimension value of 1 at a specific index.

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Output: Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7.])
Previous shape: torch.Size([7])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7.]])
New shape: torch.Size([1, 7])

You can also **rearrange the order of axes values** with ```torch.permute(input, dims)```, where the ```input``` gets turned into a view with new ```dims```.

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Output: Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])

**Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.**

#### Indexing(selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row)

In [ ]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

Output: (tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))


Indexing values goes outer dimension -> inner dimension (check out the square brackets).

In [ ]:
# Let's index bracket by bracket
print(f"First square bracket:\n{x[0]}") 
print(f"Second square bracket: {x[0][0]}") 
print(f"Third square bracket: {x[0][0][0]}")

First square bracket:
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Second square bracket: tensor([1, 2, 3])
Third square bracket: 1et: 1cket: 1

You can also use ```:``` to specify "all values in this dimension" and then use a comma (```,```) to add another dimension.

In [ ]:
# Get all values of 0th dimension and the 0 index of 1st dimension
x[:, 0]

Output: tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

Output: tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

Output: tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
x[0, 0, :] # same as x[0][0]

Output: tensor([1, 2, 3])

#### PyTorch tensors & Numpy

The two main methods you'll want to use for NumPy to PyTorch are:
1. ```torch.from_numpy(ndarray)``` - NumPy array -> PyTorch tensor
2. ```torch.Tensor.numpy()``` - PyTorch tensor -> NumPy array

In [ ]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

Output: (array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

Because we reassigned ```tensor``` above, if you change the tensor, the array stays the same.

#### Reproducibility (trying to take the random out of random)

What if you want to creat two random tensors with **the same values**. As in, the tensors would still contain random values but they would be of the same flavour. That's where ```torch.manual_seed(seed)``` comes in, where ```seed``` is an integer that flavours the randomness.

In [ ]:
import torch
import random

RANDOM_SEED = 42
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
torch.random.manual_seed(seed=RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Output: Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

#### Running tensors on GPUs

##### 1. Getting a GPU

To check if you've got access to a Nvidia GPU, you can run ```!nvidia-smi``` where the ```!``` means "run this on the command line".

##### 2. Getting PyTorch to run on the GPU

Getting PyTorch to use for storing data and computing on data. To do so, you can use the ```torch.cuda``` package.

In [ ]:
import torch
torch.cuda.is_available()

Output: True

Let's create a ```device``` variable to store what kind of device is available.

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

Output: 'cuda'

You can count the number of GPUs PyTorch has access to using ```torch.cuda.device_count()```

In [ ]:
torch.cuda.device_count()

Output: 1

##### 3. Putting tensors(and models) on the GPU

You can put tensors(and models) on a specific device by calling ```to(device)``` on them.

In [ ]:
tensor = torch.tensor([1, 2, 3])

tensor_on_gpu = tensor.to(device)
tensor_on_gpu

Output: tensor([1, 2, 3], device='cuda:0')

##### 4. Moving tensors back to the CPU

To **get back to CPU** we can use ```Tensor.cpu()```

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

Output: array([1, 2, 3])


The above returns a copy of the GPU tensor in CPU memory so the original tensor is still on GPU.

In [ ]:
tensor_on_gpu

Output: tensor([1, 2, 3], device='cuda:0')